territories = {'GAU', 'RHA', 'SAM', 'VIN', 'ILL', 'LUS', 'ARM', 'GAL', 'DAM', 'ARA', 'CIR', 'SAH', 'PHA', 'MAR', 'SAG',
               'TAR', 'MAS', 'ETU', 'ROM', 'NEA', 'APU', 'RAV', 'VEN', 'DAL', 'EPI', 'ATH', 'SPA', 'MAC', 'BYZ', 'DAC',
               'CHE', 'SIP', 'BIT', 'MIL', 'ISA', 'CAP', 'ANT', 'SID', 'TYE', 'JER', 'SII', 'PET', 'NAB', 'MAU', 'CAR',
               'THA', 'NUM', 'LEP', 'CYR', 'ALE', 'MEM', 'BAY', 'THE', 'COR', 'SAD', 'SIC', 'CRE', 'CYP', 'IBE', 'BER',
               'LIG', 'TYN', 'PUN', 'ADR', 'ION', 'AUS', 'GOT', 'GOS', 'LIB', 'MES', 'AEG', 'BLA', 'MIN', 'EGY',
               'CIL', 'SYR', 'GOP', 'REE', 'BAL'}
land_locked = {'GAU', 'RHA', 'SAM', 'VIN', 'ILL', 'LUS', 'ARM', 'GAL', 'DAM', 'ARA', 'CIR', 'SAH', 'PHA', 'MAR'}
coasts = {'SAG', 'TAR', 'MAS', 'ETU', 'ROM', 'NEA', 'APU', 'RAV', 'VEN', 'DAL', 'EPI', 'ATH', 'SPA', 'MAC', 'BYZ',
          'DAC', 'CHE', 'SIP', 'BIT', 'MIL', 'ISA', 'CAP', 'ANT', 'SID', 'TYE', 'JER', 'SII', 'PET', 'NAB', 'MAU',
          'CAR', 'THA', 'NUM', 'LEP', 'CYR', 'ALE', 'MEM', 'BAY', 'THE', 'COR', 'SAD', 'SIC', 'CRE', 'CYP'}
seas = {'IBE', 'BER', 'LIG', 'TYN', 'PUN', 'ADR', 'ION', 'AUS', 'GOT', 'GOS', 'LIB', 'MES', 'AEG', 'BLA', 'MIN', 'EGY',
        'CIL', 'SYR', 'GOP', 'REE', 'BAL'}
supply_center_territories = {'VIN', 'DAM', 'CIR', 'SAG', 'MAS', 'ROM', 'NEA', 'RAV', 'DAL', 'ATH', 'SPA', 'MAC', 'BYZ',
                             'CHE', 'SIP', 'MIL', 'ANT', 'SID', 'TYE', 'JER', 'PET', 'CAR', 'THA', 'NUM', 'LEP', 'CYR',
                             'ALE', 'MEM', 'THE', 'SAD', 'SIC', 'CRE', 'CYP', 'BAL'}
land_routes = {'GAU': ['RHA', 'MAS', 'TAR', 'LUS'],
               'RHA': ['SAM', 'VIN', 'VEN', 'ETU', 'MAS', 'GAU'],
               'SAM': ['CHE', 'DAC', 'ILL', 'VIN', 'RHA'],
               'VIN': ['SAM', 'ILL', 'DAL', 'VEN', 'RHA'],
               'ILL': ['SAM', 'DAC', 'MAC', 'EPI', 'DAL', 'VIN'],
               'LUS': ['GAU', 'TAR', 'SAG'],
               'ARM': ['CHE', 'DAM', 'CAP', 'SIP'],
               'GAL': ['BIT', 'SIP', 'CAP', 'ISA', 'MIL', 'BYZ'],
               'DAM': ['ARM', 'ARA', 'SID', 'ANT', 'CAP'],
               'ARA': ['DAM', 'NAB', 'JER', 'TYE', 'SID'],
               'CIR': ['CAR', 'THA', 'NUM', 'PHA', 'SAH', 'MAU'],
               'SAH': ['CIR', 'PHA', 'BAY', 'MAU'],
               'PHA': ['NUM', 'LEP', 'MAR', 'BAY', 'SAH', 'CIR'],
               'MAR': ['CYR', 'MEM', 'BAY', 'PHA', 'LEP'],
               'SAG': ['LUS'],
               'TAR': ['GAU', 'LUS'],
               'MAS': ['GAU', 'RHA'],
               'ETU': ['RHA', 'VEN', 'RAV'],
               'ROM': ['RAV', 'APU'],
               'NEA': [],
               'APU': ['ROM'],
               'RAV': ['ROM', 'ETU'],
               'VEN': ['RHA', 'VIN', 'ETU'],
               'DAL': ['VIN', 'ILL'],
               'EPI': ['ILL', 'MAC'],
               'ATH': [],
               'SPA': [],
               'MAC': ['ILL', 'DAC', 'EPI'],
               'BYZ': ['GAL'],
               'DAC': ['SAM', 'ILL', 'MAC'],
               'CHE': ['SAM', 'ARM'],
               'SIP': ['ARM', 'CAP', 'GAL'],
               'BIT': ['GAL'],
               'MIL': ['GAL'],
               'ISA': ['GAL'],
               'CAP': ['SIP', 'ARM', 'DAM', 'GAL'],
               'ANT': ['DAM'],
               'SID': ['DAM', 'ARA'],
               'TYE': ['ARA'],
               'JER': ['ARA', 'NAB', 'PET'],
               'SII': [],
               'PET': ['JER'],
               'NAB': ['ARA', 'JER'],
               'MAU': ['CIR', 'SAH'],
               'CAR': ['CIR'],
               'THA': ['CIR'],
               'NUM': ['PHA', 'CIR'],
               'LEP': ['MAR', 'PHA'],
               'CYR': ['MEM', 'MAR'],
               'ALE': [],
               'MEM': ['MAR', 'CYR'],
               'BAY': ['MAR', 'SAH', 'PHA'],
               'THE': [],
               'COR': [],
               'SAD': [],
               'SIC': [],
               'CRE': [],
               'CYP': [],
               'BAL': []}
coast_routes = {'SAG': ['TAR', 'MAU'],
                'TAR': ['MAS', 'SAG'],
                'MAS': ['ETU', 'TAR'],
                'ETU': ['ROM', 'MAS'],
                'ROM': ['NEA', 'ETU'],
                'NEA': ['APU', 'SIC', 'ROM'],
                'APU': ['RAV', 'NEA'],
                'RAV': ['VEN', 'APU'],
                'VEN': ['DAL', 'RAV'],
                'DAL': ['EPI', 'VEN'],
                'EPI': ['ATH', 'DAL'],
                'ATH': ['MAC', 'SPA', 'EPI'],
                'SPA': ['ATH'],
                'MAC': ['BYZ', 'ATH'],
                'BYZ': ['DAC', 'BIT', 'MIL', 'MAC'],
                'DAC': ['CHE', 'BYZ'],
                'CHE': ['SIP', 'DAC'],
                'SIP': ['BIT', 'CHE'],
                'BIT': ['BYZ', 'SIP'],
                'MIL': ['ISA', 'BYZ'],
                'ISA': ['CAP', 'MIL'],
                'CAP': ['ANT', 'ISA'],
                'ANT': ['SID', 'CAP'],
                'SID': ['TYE', 'ANT'],
                'TYE': ['JER', 'SID'],
                'JER': ['SII', 'TYE'],
                'SII': ['THE', 'ALE', 'JER', 'PET'],
                'PET': ['SII', 'NAB'],
                'NAB': ['PET'],
                'MAU': ['CAR', 'SAG'],
                'CAR': ['THA', 'MAU'],
                'THA': ['NUM', 'CAR'],
                'NUM': ['LEP', 'THA'],
                'LEP': ['CYR', 'NUM'],
                'CYR': ['ALE', 'LEP'],
                'ALE': ['SII', 'THE', 'MEM', 'CYR'],
                'MEM': ['BAY', 'THE', 'ALE'],
                'BAY': ['THE', 'MEM'],
                'THE': ['SII', 'BAY', 'MEM', "ALE"],
                'COR': ['SAD'],
                'SAD': ['COR'],
                'SIC': ['NEA'],
                'CRE': [],
                'CYP': [],
                'BAL': []}
sea_routes = {'IBE': ['SAG', 'BER', 'MAU'],
              'BER': ['LIG', 'SAD', 'PUN', 'CAR', 'MAU', 'IBE', 'SAG', 'BAL'],
              'LIG': ['MAS', 'ETU', 'ROM', 'COR', 'TYN', 'SAD', 'BER', 'BAL', 'TAR'],
              'TYN': ['ROM', 'NEA', 'AUS', 'SIC', 'PUN', 'SAD', 'LIG', 'COR'],
              'PUN': ['SAD', 'TYN', 'SIC', 'AUS', 'GOT', 'THA', 'CAR', 'BER'],
              'ADR': ['VEN', 'DAL', 'EPI', 'ION', 'APU', 'RAV'],
              'ION': ['ADR', 'EPI', 'ATH', 'SPA', 'MES', 'AUS', 'NEA', 'APU'],
              'AUS': ['NEA', 'ION', 'MES', 'LIB', 'GOT', 'PUN', 'SIC', 'TYN'],
              'GOT': ['AUS', 'MES', 'LIB', 'GOS', 'LEP', 'NUM', 'THA', 'PUN'],
              'GOS': ['LIB', 'CYR', 'LEP', 'GOT'],
              'LIB': ['MES', 'CRE', 'EGY', 'ALE', 'CYR', 'GOS', 'GOT', 'AUS'],
              'MES': ['ION', 'SPA', 'AEG', 'CRE', 'LIB', 'GOT', 'AUS'],
              'AEG': ['MAC', 'BYZ', 'MIL', 'MIN', 'CRE', 'MES', 'SPA', 'ATH'],
              'BLA': ['CHE', 'SIP', 'BIT', 'BYZ', 'DAC'],
              'MIN': ['MIL', 'CIL', 'EGY', 'CRE', 'AEG'],
              'EGY': ['MIN', 'CIL', 'CYP', 'SYR', 'GOP', 'ALE', 'LIB', 'CRE'],
              'CIL': ['ISA', 'CAP', 'ANT', 'SID', 'SYR', 'CYP', 'EGY', 'MIN', 'MIL'],
              'SYR': ['CIL', 'SID', 'TYE', 'JER', 'GOP', 'EGY', 'CYP'],
              'GOP': ['SYR', 'JER', 'SII', 'THE', 'ALE', 'EGY'],
              'REE': ['SII', 'PET', 'NAB', 'THE'],
              'BAL': ['TAR', 'LIG', 'BER', 'SAG'],
              'SAG': ['BAL', 'BER', 'IBE'],
              'TAR': ['LIG', 'BAL'],
              'MAS': ['LIG'],
              'ETU': ['LIG'],
              'ROM': ['TYN', 'LIG'],
              'NEA': ['ION', 'AUS', 'TYN'],
              'APU': ['ADR', 'ION'],
              'RAV': ['ADR'],
              'VEN': ['ADR'],
              'DAL': ['ADR'],
              'EPI': ['ION', 'ADR'],
              'ATH': ['AEG', 'ION'],
              'SPA': ['AEG', 'MES', 'ION'],
              'MAC': ['AEG'],
              'BYZ': ['BLA', 'AEG'],
              'DAC': ['BLA'],
              'CHE': ['BLA'],
              'SIP': ['BLA'],
              'BIT': ['BLA'],
              'MIL': ['CIL', 'MIN', 'AEG'],
              'ISA': ['CIL'],
              'CAP': ['CIL'],
              'ANT': ['CIL'],
              'SID': ['SYR', 'CIL'],
              'TYE': ['SYR'],
              'JER': ['GOP', 'SYR'],
              'SII': ['GOP', 'REE'],
              'PET': ['REE'],
              'NAB': ['REE'],
              'MAU': ['IBE', 'BER'],
              'CAR': ['PUN', 'BER'],
              'THA': ['GOT', 'PUN'],
              'NUM': ['GOT'],
              'LEP': ['GOT', 'GOS'],
              'CYR': ['LIB', 'GOS'],
              'ALE': ['EGY', 'GOP', 'LIB'],
              'MEM': [],
              'BAY': [],
              'THE': ['GOP', 'REE'],
              'COR': ['LIG', 'TYN'],
              'SAD': ['LIG', 'TYN', 'PUN', 'BER'],
              'SIC': ['TYN', 'AUS', 'PUN'],
              'CRE': ['AEG', 'MIN', 'EGY', 'LIB', 'MES'],
              'CYP': ['CIL', 'SYR', 'EGY']}

starting_supply_centers = {'red': {'NEA', 'ROM', 'RAV'},
                           'blue': {'THA', 'CIR', 'CAR'},
                           'green': {'SPA', 'ATH', 'MAC'},
                           'black': {'SID', 'ANT', 'DAM'},
                           'yellow': {'ALE', 'MEM', 'THE'}}
starting_units = {'red': {('F', 'NEA'), ('A', 'ROM'), ('A', 'RAV')},  # rome
                  'blue': {('F', 'THA'), ('A', 'CIR'), ('A', 'CAR')},  # carthage
                  'green': {('F', 'SPA'), ('A', 'ATH'), ('A', 'MAC')},  # greece
                  'black': {('F', 'SID'), ('A', 'ANT'), ('A', 'DAM')},  # persia
                  'yellow': {('F', 'ALE'), ('A', 'MEM'), ('A', 'THE')}}  # egypt

territories2 = {'PAR', 'BUR', 'RUH', 'SIL', 'WAR', 'MOS', 'UKR', 'MUN', 'BOH', 'GAL', 'TYR', 'VIE', 'BUD', 'SER', 'CLY',
                'EDI', 'YOR', 'LON', 'WAL', 'LVP', 'STP', 'NOR', 'SWE', 'FIN', 'LVN', 'PRU', 'BER', 'KIE', 'DEN', 'HOL',
                'BEL', 'PIC', 'BRE', 'GAS', 'SPA', 'POR', 'MAR', 'PIE', 'TUS', 'ROM', 'NEA', 'APU', 'VEN', 'TRI', 'ALB',
                'GRE', 'BUL', 'CON', 'SMY', 'SYR', 'ANK', 'ARM', 'SEV', 'RUM', 'NAF', 'TUN', 'NAO', 'NRG', 'BAR', 'MID',
                'IRI', 'ENG', 'NTH', 'HEL', 'SKA', 'BAL', 'BOT', 'GOL', 'WES', 'TYN', 'ION', 'ADR', 'AEG', 'BLA', 'EAS'}
land_locked2 = {'PAR', 'BUR', 'RUH', 'SIL', 'WAR', 'MOS', 'UKR', 'MUN', 'BOH', 'GAL', 'TYR', 'VIE', 'BUD', 'SER'}
coasts2 = {'CLY', 'EDI', 'YOR', 'LON', 'WAL', 'LVP', 'STP', 'NOR', 'SWE', 'FIN', 'LVN', 'PRU', 'BER', 'KIE', 'DEN',
           'HOL', 'BEL', 'PIC', 'BRE', 'GAS', 'SPA', 'POR', 'MAR', 'PIE', 'TUS', 'ROM', 'NEA', 'APU', 'VEN', 'TRI',
           'ALB', 'GRE', 'BUL', 'CON', 'SMY', 'SYR', 'ANK', 'ARM', 'SEV', 'RUM', 'NAF', 'TUN'}
seas2 = {'NAO', 'NRG', 'BAR', 'MID', 'IRI', 'ENG', 'NTH', 'HEL', 'SKA', 'BAL', 'BOT', 'GOL', 'WES', 'TYN', 'ION', 'ADR',
         'AEG', 'BLA', 'EAS'}
supply_center_territories2 = {'PAR', 'WAR', 'MOS', 'MUN', 'VIE', 'BUD', 'SER', 'EDI', 'LON', 'LVP', 'STP', 'NOR', 'SWE',
                              'BER', 'KIE', 'DEN', 'HOL', 'BEL', 'BRE', 'SPA', 'POR', 'MAR', 'ROM', 'NEA', 'VEN', 'TRI',
                              'GRE', 'BUL', 'CON', 'SMY', 'ANK', 'RUM', 'TUN'}
land_routes2 = {'PAR': ['PIC', 'BUR', 'GAS', 'BRE'],
                'BUR': ['BEL', 'RUH', 'MUN', 'MAR', 'GAS', 'PAR', 'PIC'],
                'RUH': ['KIE', 'MUN', 'BUR', 'BEL', 'HOL'],
                'SIL': ['BER', 'PRU', 'WAR', 'GAL', 'BOH', 'MUN'],
                'WAR': ['PRU', 'LVN', 'MOS', 'UKR', 'GAL', 'SIL'],
                'MOS': ['STP', 'SEV', 'UKR', 'WAR', 'LVN'],
                'UKR': ['MOS', 'SEV', 'RUM', 'GAL', 'WAR'],
                'MUN': ['KIE', 'SIL', 'BOH', 'TYR', 'BUR', 'RUH'],
                'BOH': ['SIL', 'GAL', 'VIE', 'TYR', 'MUN'],
                'GAL': ['WAR', 'UKR', 'RUM', 'BUD', 'VIE', 'BOH', 'SIL'],
                'TYR': ['MUN', 'BOH', 'VIE', 'TRI', 'VEN', 'PIE'],
                'VIE': ['BOH', 'GAL', 'BUD', 'TRI', 'TRY'],
                'BUD': ['GAL', 'RUM', 'SER', 'TRI', 'VIE'],
                'SER': ['BUD', 'RUM', 'BUL', 'GRE', 'ALB', 'TRI'],
                'CLY': [],
                'EDI': ['LVP'],
                'YOR': ['WAL', 'LVP'],
                'LON': [],
                'WAL': ['YOR'],
                'LVP': ['EDI', 'YOR'],
                'STP': ['MOS'],
                'NOR': ['FIN'],
                'SWE': [],
                'FIN': ['NOR'],
                'LVN': ['MOS', 'WAR'],
                'PRU': ['WAR', 'SIL'],
                'BER': ['SIL', 'MUN'],
                'KIE': ['MUN', 'RUH'],
                'DEN': [],
                'HOL': ['RUH'],
                'BEL': ['RUH', 'BUR'],
                'PIC': ['BUR', 'PAR'],
                'BRE': ['PAR'],
                'GAS': ['PAR', 'BUR', 'MAR'],
                'SPA': [],
                'POR': [],
                'MAR': ['BUR', 'GAS'],
                'PIE': ['TYR', 'VEN'],
                'TUS': ['VEN'],
                'ROM': ['VEN', 'APU'],
                'NEA': [],
                'APU': ['ROM'],
                'VEN': ['TYR', 'TUS', 'ROM', 'PIE'],
                'TRI': ['VIE', 'BUD', 'SER', 'TYR'],
                'ALB': ['SER'],
                'GRE': ['SER'],
                'BUL': ['SER'],
                'CON': [],
                'SMY': ['ANK', 'ARM'],
                'SYR': ['ARM'],
                'ANK': ['SMY'],
                'ARM': ['SYR', 'SMY'],
                'SEV': ['MOS', 'UKR'],
                'RUM': ['UKR', 'SER', 'BUD', 'GAL'],
                'NAF': [],
                'TUN': []}
coast_routes2 = {'CLY': ['EDI', 'LVP'],
                 'EDI': ['YOR', 'CLY'],
                 'YOR': ['EDI', 'YOR'],
                 'LON': ['YOR', 'WAL'],
                 'WAL': ['LVP', 'LON'],
                 'LVP': ['CLY', 'WAL'],
                 'STP': ['LVN', 'FIN', 'NOR'],  # HAS 2 COASTS
                 'NOR': ['STP', 'SWE'],  # CONNECTS TO NORTH COAST OF ST PETERSBURG
                 'SWE': ['FIN', 'DEN', 'NOR'],
                 'FIN': ['STP', 'SWE'],  # CONNECTS TO SOUTH COAST OF ST PETERSBURG
                 'LVN': ['STP', 'PRU'],  # CONNECTS TO SOUTH COAST OF ST PETERSBURG
                 'PRU': ['LVN', 'BER'],
                 'BER': ['PRU', 'KIE'],
                 'KIE': ['DEN', 'BER', 'HOL'],
                 'DEN': ['SWE', 'KIE'],
                 'HOL': ['KIE', 'BEL'],
                 'BEL': ['HOL', 'PIC'],
                 'PIC': ['BEL', 'BRE'],
                 'BRE': ['PIC', 'GAS'],
                 'GAS': ['BRE', 'SPA'],  # CONNECTS TO NORTH COAST OF SPAIN
                 'SPA': ['GAS', 'MAR', 'POR'],  # HAS 2 COASTS
                 'POR': ['SPA'],  # CONNECTS TO BOTH COASTS OF SPAIN
                 'MAR': ['PIE', 'SPA'],  # CONNECTS TO SOUTH COAST OF SPAIN
                 'PIE': ['TUS', 'MAR'],
                 'TUS': ['POM', 'PIE'],
                 'ROM': ['NEA', 'TUS'],
                 'NEA': ['APU', 'ROM'],
                 'APU': ['NEA', 'VEN'],
                 'VEN': ['TRI', 'APU'],
                 'TRI': ['ALB', 'VEN'],
                 'ALB': ['GRE', 'TRI'],
                 'GRE': ['BUL', 'ALB'],  # CONNECTS TO SOUTH COAST OF BULGARIA
                 'BUL': ['RUM', 'CON', 'GRE'],  # HAS 2 COASTS
                 'CON': ['ANK', 'SMY', 'BUL'],  # CONNECTS TO BOTH COASTS OF BULGARIA
                 'SMY': ['CON', 'SYR'],
                 'SYR': ['SMY'],
                 'ANK': ['ARM', 'CON'],
                 'ARM': ['SEV', 'ANK'],
                 'SEV': ['ARM', 'RUM'],
                 'RUM': ['SEV', 'BUL'],  # CONNECTS TO NORTH COAST OF BULGARIA
                 'NAF': ['TUN'],
                 'TUN': ['NAF']}
sea_routes2 = {'NAO': ['NRG', 'CLY', 'LVP', 'IRI', 'MID'],
               'NRG': ['BAR', 'NOR', 'NTH', 'EDI', 'NAO'],
               'BAR': ['STP', 'NOR', 'NRG'],  # CONNECTS TO NORTH COAST OF ST PETERSBURG
               'MID': ['NAO', 'IRI', 'ENG', 'BRE', 'GAS', 'SPA', 'POR', 'WES', 'NAF'],
               # CONNECTS TO BOTH COASTS OF SPAIN
               'IRI': ['NAO', 'LVP', 'WAL', 'ENG', 'MID'],
               'ENG': ['WAL', 'LON', 'NTH', 'BEL', 'PIC', 'BRE', 'MID'],
               'NTH': ['NRG', 'NOR', 'SKA', 'DEN', 'HEL', 'HOL', 'BEL', 'ENG', 'LON', 'YOR', 'EDI'],
               'HEL': ['NTH', 'DEN', 'KIE', 'HOL'],
               'SKA': ['NOR', 'SWE', 'DEN', 'NTH'],
               'BAL': ['SWE', 'BOT', 'LVN', 'PRU', 'BER', 'KIE', 'DEN'],  # CONNNCTS TO SOUTH COAST OF ST PETERSBURG
               'BOT': ['FIN', 'STP', 'LVN', 'BAL', 'SWE'],
               'GOL': ['MAR', 'PIE', 'TUS', 'TYN', 'WES', 'SPA'],  # CONNECTS TO SOUTH COAST OF SPAIN
               'WES': ['SPA', 'GOL', 'TYN', 'TUN', 'NAF', 'MID'],  # CONNECTS TO SOUTH COAST OF SPAIN
               'TYN': ['GOL', 'TUS', 'ROM', 'NEA', 'ION', 'TUN', 'WES'],
               'ION': ['NEA', 'APU', 'ADR', 'ALB', 'GRE', 'AEG', 'EAS', 'TUN', 'TYN'],
               'ADR': ['TRI', 'ALB', 'ION', 'APU', 'VEN'],
               'AEG': ['BUL', 'CON', 'SMY', 'EAS', 'ION', 'GRE'],  # CONNECTS TO SOUTH COAST OF BULGARIA
               'BLA': ['SEV', 'ARM', 'ANK', 'CON', 'BUL', 'RUM'],  # CONNECTS TO NORTH COAST OF BULGARIA
               'EAS': ['SMY', 'SYR', 'ION', 'AEG'],
               'CLY': ['NAO', 'IRI'],
               'EDI': ['NOR', 'NTH'],
               'YOR': ['NTH'],
               'LON': ['NTH', 'ENG'],
               'WAL': ['ENG', 'IRI'],
               'LVP': ['IRI', 'NAO'],
               'STP': ['BAR', 'BOT'],  # HAS 2 COASTS
               'NOR': ['NRG', 'BAR', 'SKA', 'NTH'],
               'SWE': ['BOT', 'BAL', 'SKA'],
               'FIN': ['BOT'],
               'LVN': ['BOT', 'BAL'],
               'PRU': ['BAL'],
               'BER': ['BAL'],
               'KIE': ['BAL', 'HEL'],
               'DEN': ['SKA', 'BAL', 'HEL', 'NTH'],
               'HOL': ['HEL', 'NTH'],
               'BEL': ['NTH', 'ENG'],
               'PIC': ['ENG'],
               'BRE': ['ENG', 'MID'],
               'GAS': ['MID'],
               'SPA': ['MID', 'GOL', 'WES'],  # HAS 2 COASTS
               'POR': ['MID'],
               'MAR': ['GOL'],
               'PIE': ['GOL'],
               'TUS': ['TYN', 'GOL'],
               'ROM': ['TYN'],
               'NEA': ['ION', 'TYN'],
               'APU': ['ADR', 'ION'],
               'VEN': ['ADR'],
               'TRI': ['ADR'],
               'ALB': ['ION', 'ADR'],
               'GRE': ['AEG', 'ION'],
               'BUL': ['BLA', 'AEG'],  # HAS 2 COASTS
               'CON': ['BLA', 'AEG'],
               'SMY': ['EAS', 'AEG'],
               'SYR': ['EAS'],
               'ANK': ['BLA'],
               'ARM': ['BLA'],
               'SEV': ['BLA'],
               'RUM': ['BLA'],
               'NAF': ['WES', 'MID'],
               'TUN': ['WES', 'TYN', 'ION']}
starting_supply_centers2 = {'red': {'TRI', 'VIE', 'BUD'},  # austria
                            'pink': {'LON', 'EDI', 'LVP'},  # england
                            'blue': {'BRE', 'PAR', 'MAR'},  # france
                            'brown': {'KIE', 'BER', 'MUN'},  # germany
                            'green': {'NEA', 'ROM', 'VEN'},  # italy
                            'black': {'SEV', 'STP', 'MOS', 'WAR'},  # russia
                            'yellow': {'ANK', 'CON', 'SMY'}}  # turkey
units_by_color2 = {'red': {('F', 'TRI'), ('A', 'VIE'), ('A', 'BUD')},  # austria
                   'pink': {('F', 'LON'), ('A', 'EDI'), ('A', 'LVP')},  # england
                   'blue': {('F', 'BRE'), ('A', 'PAR'), ('A', 'MAR')},  # france
                   'brown': {('F', 'KIE'), ('A', 'BER'), ('A', 'MUN')},  # germany
                   'green': {('F', 'NEA'), ('A', 'ROM'), ('A', 'VEN')},  # italy
                   'black': {('F', 'SEV'), ('F', 'STP'), ('A', 'MOS'), ('A', 'WAR')},  # russia
                   'yellow': {('F', 'ANK'), ('A', 'CON'), ('A', 'SMY')}}  # turkey

# TODO: need special code for bulgaria, spain, and st. petersburg since they have 2 coasts each
#  think of structure for game state to be generic to board variant
